//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ConexionCuentaCorriente.GetOpenItems {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'Policy' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Z_ROL_02_WS_GET_ACC_OPENITEMS", Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_ROL_02_WS_GET_ACC_OPENITEMS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallZ_ROL_02_WS_GET_ACC_OPENITEMSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Z_ROL_02_WS_GET_ACC_OPENITEMS() {
            this.Url = global::ConexionCuentaCorriente.Properties.Settings.Default.ConexionCuentaCorriente_GetOpenItems_Z_ROL_02_WS_GET_ACC_OPENITEMS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallZ_ROL_02_WS_GET_ACC_OPENITEMSCompletedEventHandler CallZ_ROL_02_WS_GET_ACC_OPENITEMSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:Z_ROL_02_WS_GET_ACC_OPENITEMS:Z_ROL_02_WS_" +
            "GET_ACC_OPENITEMSRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("Z_ROL_02_WS_GET_ACC_OPENITEMSResponse", Namespace="urn:sap-com:document:sap:rfc:functions")]
        public Z_ROL_02_WS_GET_ACC_OPENITEMSResponse CallZ_ROL_02_WS_GET_ACC_OPENITEMS([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")] Z_ROL_02_WS_GET_ACC_OPENITEMS1 Z_ROL_02_WS_GET_ACC_OPENITEMS) {
            object[] results = this.Invoke("CallZ_ROL_02_WS_GET_ACC_OPENITEMS", new object[] {
                        Z_ROL_02_WS_GET_ACC_OPENITEMS});
            return ((Z_ROL_02_WS_GET_ACC_OPENITEMSResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CallZ_ROL_02_WS_GET_ACC_OPENITEMSAsync(Z_ROL_02_WS_GET_ACC_OPENITEMS1 Z_ROL_02_WS_GET_ACC_OPENITEMS) {
            this.CallZ_ROL_02_WS_GET_ACC_OPENITEMSAsync(Z_ROL_02_WS_GET_ACC_OPENITEMS, null);
        }
        
        /// <remarks/>
        public void CallZ_ROL_02_WS_GET_ACC_OPENITEMSAsync(Z_ROL_02_WS_GET_ACC_OPENITEMS1 Z_ROL_02_WS_GET_ACC_OPENITEMS, object userState) {
            if ((this.CallZ_ROL_02_WS_GET_ACC_OPENITEMSOperationCompleted == null)) {
                this.CallZ_ROL_02_WS_GET_ACC_OPENITEMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallZ_ROL_02_WS_GET_ACC_OPENITEMSOperationCompleted);
            }
            this.InvokeAsync("CallZ_ROL_02_WS_GET_ACC_OPENITEMS", new object[] {
                        Z_ROL_02_WS_GET_ACC_OPENITEMS}, this.CallZ_ROL_02_WS_GET_ACC_OPENITEMSOperationCompleted, userState);
        }
        
        private void OnCallZ_ROL_02_WS_GET_ACC_OPENITEMSOperationCompleted(object arg) {
            if ((this.CallZ_ROL_02_WS_GET_ACC_OPENITEMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallZ_ROL_02_WS_GET_ACC_OPENITEMSCompleted(this, new CallZ_ROL_02_WS_GET_ACC_OPENITEMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_ROL_02_WS_GET_ACC_OPENITEMS1 {
        
        private string cOMPANYCODEField;
        
        private ZSD02_WS_CLIENTES_RANGES[] i_T_CLIENTES_RANGESField;
        
        private string kEYDATEField;
        
        private string nOTEDITEMSField;
        
        private string sECINDEXField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMPANYCODE {
            get {
                return this.cOMPANYCODEField;
            }
            set {
                this.cOMPANYCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSD02_WS_CLIENTES_RANGES[] I_T_CLIENTES_RANGES {
            get {
                return this.i_T_CLIENTES_RANGESField;
            }
            set {
                this.i_T_CLIENTES_RANGESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KEYDATE {
            get {
                return this.kEYDATEField;
            }
            set {
                this.kEYDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOTEDITEMS {
            get {
                return this.nOTEDITEMSField;
            }
            set {
                this.nOTEDITEMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SECINDEX {
            get {
                return this.sECINDEXField;
            }
            set {
                this.sECINDEXField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD02_WS_CLIENTES_RANGES {
        
        private string kUNNR_DESDEField;
        
        private string kUNNR_HASTAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KUNNR_DESDE {
            get {
                return this.kUNNR_DESDEField;
            }
            set {
                this.kUNNR_DESDEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KUNNR_HASTA {
            get {
                return this.kUNNR_HASTAField;
            }
            set {
                this.kUNNR_HASTAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZROL02_WS_ACC_PARTIDAS {
        
        private string cOMP_CODEField;
        
        private string cUSTOMERField;
        
        private string sP_GL_INDField;
        
        private string cLR_DOC_NOField;
        
        private string aLLOC_NMBRField;
        
        private string fISC_YEARField;
        
        private string dOC_NOField;
        
        private string pSTNG_DATEField;
        
        private string dOC_DATEField;
        
        private string cURRENCYField;
        
        private string lOC_CURRCYField;
        
        private string rEF_DOC_NOField;
        
        private string dOC_TYPEField;
        
        private string fIS_PERIODField;
        
        private string dB_CR_INDField;
        
        private string bUS_AREAField;
        
        private string tAX_CODEField;
        
        private decimal lC_AMOUNTField;
        
        private decimal aMT_DOCCURField;
        
        private string iTEM_TEXTField;
        
        private string bLINE_DATEField;
        
        private string pMNTTRMSField;
        
        private decimal dSCT_DAYS1Field;
        
        private decimal dSCT_DAYS2Field;
        
        private decimal nETTERMSField;
        
        private string iNV_REFField;
        
        private string iNV_YEARField;
        
        private string iNV_ITEMField;
        
        private string rEF_KEY_2Field;
        
        private string t_CURRENCYField;
        
        private decimal aMOUNTField;
        
        private decimal nET_AMOUNTField;
        
        private string rEF_DOCField;
        
        private string rEF_DOC_NO_LONGField;
        
        private string bILL_DOCField;
        
        private decimal lC_AMOUNT_LONGField;
        
        private decimal aMT_DOCCUR_LONGField;
        
        private decimal aMOUNT_LONGField;
        
        private decimal nET_AMOUNT_LONGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMP_CODE {
            get {
                return this.cOMP_CODEField;
            }
            set {
                this.cOMP_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CUSTOMER {
            get {
                return this.cUSTOMERField;
            }
            set {
                this.cUSTOMERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SP_GL_IND {
            get {
                return this.sP_GL_INDField;
            }
            set {
                this.sP_GL_INDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CLR_DOC_NO {
            get {
                return this.cLR_DOC_NOField;
            }
            set {
                this.cLR_DOC_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ALLOC_NMBR {
            get {
                return this.aLLOC_NMBRField;
            }
            set {
                this.aLLOC_NMBRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FISC_YEAR {
            get {
                return this.fISC_YEARField;
            }
            set {
                this.fISC_YEARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DOC_NO {
            get {
                return this.dOC_NOField;
            }
            set {
                this.dOC_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PSTNG_DATE {
            get {
                return this.pSTNG_DATEField;
            }
            set {
                this.pSTNG_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DOC_DATE {
            get {
                return this.dOC_DATEField;
            }
            set {
                this.dOC_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CURRENCY {
            get {
                return this.cURRENCYField;
            }
            set {
                this.cURRENCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOC_CURRCY {
            get {
                return this.lOC_CURRCYField;
            }
            set {
                this.lOC_CURRCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REF_DOC_NO {
            get {
                return this.rEF_DOC_NOField;
            }
            set {
                this.rEF_DOC_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DOC_TYPE {
            get {
                return this.dOC_TYPEField;
            }
            set {
                this.dOC_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FIS_PERIOD {
            get {
                return this.fIS_PERIODField;
            }
            set {
                this.fIS_PERIODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DB_CR_IND {
            get {
                return this.dB_CR_INDField;
            }
            set {
                this.dB_CR_INDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUS_AREA {
            get {
                return this.bUS_AREAField;
            }
            set {
                this.bUS_AREAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TAX_CODE {
            get {
                return this.tAX_CODEField;
            }
            set {
                this.tAX_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal LC_AMOUNT {
            get {
                return this.lC_AMOUNTField;
            }
            set {
                this.lC_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal AMT_DOCCUR {
            get {
                return this.aMT_DOCCURField;
            }
            set {
                this.aMT_DOCCURField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ITEM_TEXT {
            get {
                return this.iTEM_TEXTField;
            }
            set {
                this.iTEM_TEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BLINE_DATE {
            get {
                return this.bLINE_DATEField;
            }
            set {
                this.bLINE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PMNTTRMS {
            get {
                return this.pMNTTRMSField;
            }
            set {
                this.pMNTTRMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal DSCT_DAYS1 {
            get {
                return this.dSCT_DAYS1Field;
            }
            set {
                this.dSCT_DAYS1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal DSCT_DAYS2 {
            get {
                return this.dSCT_DAYS2Field;
            }
            set {
                this.dSCT_DAYS2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal NETTERMS {
            get {
                return this.nETTERMSField;
            }
            set {
                this.nETTERMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INV_REF {
            get {
                return this.iNV_REFField;
            }
            set {
                this.iNV_REFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INV_YEAR {
            get {
                return this.iNV_YEARField;
            }
            set {
                this.iNV_YEARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INV_ITEM {
            get {
                return this.iNV_ITEMField;
            }
            set {
                this.iNV_ITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REF_KEY_2 {
            get {
                return this.rEF_KEY_2Field;
            }
            set {
                this.rEF_KEY_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string T_CURRENCY {
            get {
                return this.t_CURRENCYField;
            }
            set {
                this.t_CURRENCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal AMOUNT {
            get {
                return this.aMOUNTField;
            }
            set {
                this.aMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal NET_AMOUNT {
            get {
                return this.nET_AMOUNTField;
            }
            set {
                this.nET_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REF_DOC {
            get {
                return this.rEF_DOCField;
            }
            set {
                this.rEF_DOCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REF_DOC_NO_LONG {
            get {
                return this.rEF_DOC_NO_LONGField;
            }
            set {
                this.rEF_DOC_NO_LONGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BILL_DOC {
            get {
                return this.bILL_DOCField;
            }
            set {
                this.bILL_DOCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal LC_AMOUNT_LONG {
            get {
                return this.lC_AMOUNT_LONGField;
            }
            set {
                this.lC_AMOUNT_LONGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal AMT_DOCCUR_LONG {
            get {
                return this.aMT_DOCCUR_LONGField;
            }
            set {
                this.aMT_DOCCUR_LONGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal AMOUNT_LONG {
            get {
                return this.aMOUNT_LONGField;
            }
            set {
                this.aMOUNT_LONGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal NET_AMOUNT_LONG {
            get {
                return this.nET_AMOUNT_LONGField;
            }
            set {
                this.nET_AMOUNT_LONGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZROL02_WS_GET_ACC_ERR_E {
        
        private string mSGNRField;
        
        private string eRRORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGNR {
            get {
                return this.mSGNRField;
            }
            set {
                this.mSGNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_ROL_02_WS_GET_ACC_OPENITEMSResponse {
        
        private ZROL02_WS_GET_ACC_ERR_E[] e_T_ERRORESField;
        
        private ZROL02_WS_ACC_PARTIDAS[] e_T_PARTIDASField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZROL02_WS_GET_ACC_ERR_E[] E_T_ERRORES {
            get {
                return this.e_T_ERRORESField;
            }
            set {
                this.e_T_ERRORESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZROL02_WS_ACC_PARTIDAS[] E_T_PARTIDAS {
            get {
                return this.e_T_PARTIDASField;
            }
            set {
                this.e_T_PARTIDASField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CallZ_ROL_02_WS_GET_ACC_OPENITEMSCompletedEventHandler(object sender, CallZ_ROL_02_WS_GET_ACC_OPENITEMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallZ_ROL_02_WS_GET_ACC_OPENITEMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallZ_ROL_02_WS_GET_ACC_OPENITEMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Z_ROL_02_WS_GET_ACC_OPENITEMSResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Z_ROL_02_WS_GET_ACC_OPENITEMSResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591