//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaCorriente_Descarga
    {
        public int Id { get; set; }
        public string Alloc_Nmbr { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Amount_Long { get; set; }
        public Nullable<decimal> Amt_Doccur { get; set; }
        public Nullable<decimal> Amt_Doccur_Long { get; set; }
        public string Bill_Doc { get; set; }
        public Nullable<System.DateTime> Bline_Date { get; set; }
        public string Bus_Area { get; set; }
        public string Clr_Doc_No { get; set; }
        public string Comp_Code { get; set; }
        public string Currency { get; set; }
        public string Customer { get; set; }
        public string Db_Cr_Ind { get; set; }
        public Nullable<System.DateTime> Doc_Date { get; set; }
        public string Doc_no { get; set; }
        public string Doc_Type { get; set; }
        public Nullable<decimal> Dsct_Days1 { get; set; }
        public Nullable<decimal> Dsct_Days2 { get; set; }
        public string Fisc_Year { get; set; }
        public string Fis_Period { get; set; }
        public string Inv_Item { get; set; }
        public string Inv_Ref { get; set; }
        public string Inv_Year { get; set; }
        public string Item_Text { get; set; }
        public Nullable<decimal> Lc_Amount { get; set; }
        public Nullable<decimal> Lc_Amount_long { get; set; }
        public string Loc_Currcy { get; set; }
        public Nullable<decimal> Netterms { get; set; }
        public Nullable<decimal> Net_Amount { get; set; }
        public Nullable<decimal> Net_Amount_Long { get; set; }
        public string Pmnttrms { get; set; }
        public Nullable<System.DateTime> Pstng_Date { get; set; }
        public string Ref_Doc { get; set; }
        public string Ref_Doc_No { get; set; }
        public string Ref_Doc_No_Long { get; set; }
        public string Ref_Key_2 { get; set; }
        public string Sp_Gl_Ind { get; set; }
        public string Tax_Code { get; set; }
        public string T_Currency { get; set; }
    }
}
